name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Warrant? We'd love to hear it. Please describe the problem you're trying to solve and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's frustrating or missing?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the platform does this relate to?
      options:
        - Feed / articles
        - Authentication / login
        - Subscription / payments
        - Journalist dashboard
        - Admin dashboard
        - Integrity system
        - Search
        - API
        - Infrastructure / CI
        - Other
    validations:
      required: true
